#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2018.4.11f1_7098af2f11ea"
#define UNITY_VERSION_FULL_NICE "2018.4.11f1 (7098af2f11ea)"
#define UNITY_VERSION_BLD 7379119
#define UNITY_VERSION_DATE 1570145166
#define UNITY_VERSION_WIN "2018.4.11.7379119"
#define UNITY_VERSION_BRANCH "2018.4/staging"
